# Generated by Django 4.2.2 on 2024-02-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_active", models.BooleanField(default=False)),
                ("cache_time", models.PositiveIntegerField(default=86400)),
            ],
        ),
    ]
