# Generated by Django 4.2.2 on 2024-03-04 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$",
                                message="Номер телефона должен быть в формате +7 (999) 999-99-99",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ads.advertisement",
                        verbose_name="Рекламная кампания",
                    ),
                ),
            ],
        ),
    ]
