# Generated by Django 4.2.2 on 2024-03-06 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Название",
                    ),
                ),
                (
                    "channel",
                    models.CharField(max_length=255, verbose_name="Канал продвижения"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="Бюджет"
                    ),
                ),
                ("archived", models.BooleanField(default=0, verbose_name="В архиве")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.product",
                        verbose_name="Услуга",
                    ),
                ),
            ],
        ),
    ]
